spring:   
   datasource: 
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/datacollection?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      username: root
      password: test123456
   data:
      mongodb:
         uri: mongodb://127.0.0.1:27017/database
               
mybatis:
   mapper-locations: classpath:mapper/*.xml   
         